services:
  - type: web
    name: jobsearch-api
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        sync: false
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGSMITH_ENDPOINT
        value: https://eu.api.smith.langchain.com
